### ISSUE TITLE
Code-along Files

### ISSUE THREAD

**Issue by ngevan** [learn-co-curriculum/bootstrap-navbar-code-along#1]
Hi!

The lab starts immediately assuming that we're on the same page with having all the files ready to code along with. Like the previous lesson/lab, nothing is present in the forked lab so we have to manually re-add all the files used in the Exceptional Realty project to the directory. Even then, I have to find and go into the forked lab that has all the files (I believe the "adding-responsive-features" lab) because only the latest forked labs have all the images/videos/etc. The lessons are broken up instead of us building and continuing from the same directory as the lecturer in the video. 

I don't know if this is intended for us to practice copying files through terminal or any of that sort, but I just wanted to give feedback if you want to make the lab easier to begin and follow from the start. Thank you!

**Comment by AnnJohn** [comment]
thanks @evanscloud for raising this issue. Yes, we want to improve this series of labs and will add more detailed instructions as soon as we can.

**Comment by daniellecroxton** [comment]
Bump

**Comment by jenmyers** [comment]
We have added instructions to clarify how to access the necessary files.
