### ISSUE TITLE
Forking problems

### ISSUE THREAD

**Issue by srutisriram** [learn-co-curriculum/bootstrap-navbar-code-along#2]
the repositories for all of the bootstrap lessons don't have the bootstrap or the index documents (which is fine, but then there shouldn't be green lights for forking and submitting a pull request, because I've had a lot of errors just creating my own folders and then submitting them as lessons, so end up having to copy paste the exact same folders into each empty forked repository, which wastes a lot of space on my computer)

**Comment by AnnJohn** [comment]
hi @srutisriram thanks for raising this. This issue should be fixed now; we changed everything back to Readmes so that you don't need to submit a pull request to get the tests passing. Please let us know if that's not the case. Thanks!
