### ISSUE TITLE
Video and content does not correspond

### ISSUE THREAD

**Issue by klovae** [learn-co-curriculum/bootstrap-navbar-code-along#3]
The video embedded in the lesson is actually the video from the lesson immediately prior. The YouTube link does point to the correct site, https://www.youtube.com/watch?v=bWVUo67pShU

**Comment by jenmyers** [comment]
Thanks for reporting this issue. We're aware of it and are tracking it in #12. We're closing this specific issue but you can follow progress at the other URL.

-- Flatiron Curriculum Team
