### ISSUE TITLE
issues with the last two codealongs lessons in HTML CSS session

### ISSUE THREAD

**Issue by baschenbrenner** [learn-co-curriculum/bootstrap-navbar-code-along#6]
I think these lessons are poorly setup, especially with how Jon approaches it. There is a mismatch between what the 2017 user is experiencing through learn-ide and what he is doing. I just had a lot of trouble submitting because I was working in a folder that wasn't the folder that learn-ide expected and it wouldn't let me submit and it was a big rigamarole. Flatiron can do better here.

**Comment by jenmyers** [comment]
Thanks for reporting this issue. We're aware of it and are tracking it in #12. We're closing this specific issue but you can follow progress at the other URL.

-- Flatiron Curriculum Team
