### ISSUE TITLE
Outdated Format

### ISSUE THREAD

**Issue by dkStephanos** [learn-co-curriculum/bootstrap-navbar-code-along#7]
The Bootstrap website, in addition to a fair amount of the formatting they use for the Nav bar has changed. I found it a little difficult to follow the video properly. This lesson could really use an update.

**Comment by jenmyers** [comment]
Thanks for reporting this issue. We're aware of it and are tracking it in #12. We're closing this specific issue but you can follow progress at the other URL.

-- Flatiron Curriculum Team
