### ISSUE TITLE
Have had to redo assignment 3 times

### ISSUE THREAD

**Issue by eyosef** [learn-co-curriculum/bootstrap-navbar-code-along#8]
I have had to re-do this assignment three times. I have used git clone 3 times, because Learn IDE does not appear to be able to save cloned repositories. I have followed the video three times, and after pushing my changes to the github, when I log off and log on, I have found the assignment to have never been pushed to my repository.

I have also worked with 3 technical coaches due to debugging issues with the video associated with this lab, and the previous lab. Unfortunately, despite this, the assignment was not pushed to the github repository. I would like to request that I receive credit for this lab. I have exercised flexibility in redoing the lab three times, worked with multiple coaches due to the dated videos, and I have resubmitted the lab to no avail. It seems incongruent that the videos provide enough technical issues to obscure the content of the lessons. I will not be attempting to complete this lab a 4th time.

**Comment by jenmyers** [comment]
Thanks for reporting this issue. We're aware of it and are tracking it in #12. We're closing this specific issue but you can follow progress at the other URL.

-- Flatiron Curriculum Team
