### ISSUE TITLE
Lesson missing files...

### ISSUE THREAD

**Issue by stimsong** [learn-co-curriculum/bootstrap-navbar-code-along#9]
Hello, 

I opened this similar issue with the previous lesson as well...

> Hello,
> 
> This code-along is still missing the necessary files to work on. Since Learn.co is configured to basically only work on the current lesson we are on and we aren't manually using a Git repository that we are continuing to update, this is a big problem. And it seems to have been around for a long time. 
> 
> Everything has been great up until this point but this is troubling. It makes me wonder if there are other lessons that have the same problem later on? I'm in the Community-powered version of Full-Stack Web Development, which is supposed to be the same as the Online version. Does this problem exist with the Online Web Developer program as well?
> 
> I will continue with the Community-powered course for now but this kind of issue would stop me from considering changing to the Online-version at some point.
> 
> Thanks,
> Greg

**Comment by jenmyers** [comment]
Thanks for reporting this issue. We're aware of it and are tracking it in #12. We're closing this specific issue but you can follow progress at the other URL.

-- Flatiron Curriculum Team
